server:
  port: 8080

spring:
  application:
  name: Vivacon
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.vivacon.com:5432/vivacon?useSSL=false&useUnicode=true
    username: postgres
    password: Admin123*
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
        metadata_builder_contributor: com.vivacon.common.relational_db.SQLFunctionsMetadataBuilderContributor
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${java.io.tmpdir}

vivacon:
  jwt:
    secret_salt: Vivacon@123456
    jwt_validity: 3600000 # 1000 * 60 * 60 - 1 Hour
    jwt_issuer: Vivacon_Khoa_Truc_Hung
    refresh_expiration: 360000000 # 1000 * 60 * 60 * 100- 100 Hour
  verification_token:
    expiration: 18000 # 5 * 60 * 60 - 5 minutes
  email:
    address: vivacon.service@gmail.com
    password: Admin123*

aws:
  access_key_id: AKIAV3KWG2VTG47Q667Q
  secret_access_key: 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
  s3:
    bucket: vivacon-bucket
    region: ap-southeast-1

